version: '3'
services:
  caddy:
    image: abiosoft/caddy
    restart: always
    env_file: .env
    networks:
        - front
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - caddy-logs:/var/log/caddy
      - goaccess-html:/www/goaccess
      - ./caddy-srv/:/srv
    ports:
      - 80:80
      - 443:443
      - 7890:7890
    command: --agree --conf  "/etc/Caddyfile"
  client:
    image: ammobindotca/ammobin-client
    restart: always
    networks:
       - front
    deploy:
      resources:
        limits:
          memory: 450M
    environment:
      - DONT_USE_INFLUX=true      
  api:
    env_file: .env
    image: ammobindotca/ammobin-api
    restart: always
    networks:
        - front
        - back
    deploy:
      resources:
        limits:
          memory: 500M
    depends_on:
      - redis
      - fluent
    environment:
      - DONT_USE_INFLUX=true
      - FLUENT=true
  worker:
    env_file: .env
    image: ammobindotca/ammobin-api
    restart: always
    command: npm run start:worker
    networks:
        - back
    depends_on:
      - redis
      - fluent
    environment:
      - DONT_USE_INFLUX=true
      - FLUENT=true
  refresher:
    env_file: .env
    image: ammobindotca/ammobin-api
    restart: always
    command: npm run start:refresher
    healthcheck:
      disable: true
    networks:
        - back
    depends_on:
      - redis
      - fluent
    environment:
      - FLUENT=true
  redis:
    image: redis:5-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
        - back
    deploy:
      resources:
        limits:
          memory: 200M
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  images:
    image: willnorris/imageproxy:latest
    restart: always
    networks:
        - front
    deploy:
      resources:
        limits:
          memory: 150M
    entrypoint:  /app/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers ammobin.ca
  goaccess:
    image: allinurl/goaccess
    networks:
        - front
    volumes:
      - ./goaccess.conf:/srv/data/goaccess.conf
      - goaccess-html:/srv/report
      - caddy-logs:/srv/logs
    entrypoint: goaccess --no-global-config --config-file=/srv/data/goaccess.conf --ws-url=wss://stats.ammobin.ca --output=/srv/report/index.html --log-file=/srv/logs/ammobin.log --real-time-html
  rendertron:
    image: ammobindotca/rendertron
    restart: always
    networks:
        - back
  fluent:
    image: ammobindotca/ammobin-elasticsearch-fluentd
    restart: always
    env_file: .env
    networks:
        - back
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - caddy-logs:/var/log
      - fluent-buffer:/fluentd/log/
    environment:
      - FLUENTD_CONF=fluent.conf

networks:
    back:
    front:
volumes:
    fluent-buffer:
    caddy-logs:
    goaccess-data:
    goaccess-html:
    caddy-srv:
