version: '2'
services:
  caddy:
    image: abiosoft/caddy:latest
    restart: always
    env_file: .env 
    links:
      - client
      - api
      - images
      - graphana
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy-logs:/var/log/caddy
      - ./goaccess-data/report/:/www/goaccess
    ports:
      - 80:80
      - 443:443
    command: --conf  "/etc/Caddyfile"
  client:
    image: ammobindotca/ammobin-client:latest
    restart: always
    ports:
      - 3000
  influx:
    image: influxdb:1.3-alpine
    restart: always
    volumes:
      - ./influx-data/:/var/lib/influxdb      
    ports:
      - 8086    
  api:
    env_file: .env 
    image: ammobindotca/ammobin-api:latest
    restart: always
    ports:
      - 8080
    links:
      - redis
      - influx
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  images:
    image: willnorris/imageproxy:latest
    restart: always
    entrypoint:  /go/bin/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers ammobin.ca
    ports:
      - 8080
  goaccess:
    image: allinurl/goaccess
    volumes:
      - ./goaccess-data/data:/srv/data
      - ./goaccess-data/report:/srv/report
      - ./caddy-logs:/srv/logs  
  graphana:
    image: grafana/grafana
    env_file: .env
    restart: always
    ports:
      - 3000
    volumes:
      - ./graphana:/var/lib/grafana
