version: '2.2'
services:
  caddy:
    image: abiosoft/caddy:latest
    restart: always
    env_file: .env
    links:
      - client
      - api
      - images
      - graphana
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy-logs:/var/log/caddy
      - ./goaccess-data/report/:/www/goaccess
    ports:
      - 80:80
      - 443:443
    command: --conf  "/etc/Caddyfile"
  client:
    image: ammobindotca/ammobin-client:latest
    restart: always
    init: true
    mem_limit: 250MB
    memswap_limit: 1G
    depends_on:
      - api
  influx:
    image: influxdb:1.3-alpine
    restart: always
    volumes:
      - ./influx-data/:/var/lib/influxdb
  api:
    env_file: .env
    image: ammobindotca/ammobin-api:latest
    restart: always
    init: true
    mem_reservation: 150MB
    mem_limit: 500MB
    memswap_limit: 1GB
    links:
      - redis
      - influx
    depends_on:
      - redis
      - influx
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    mem_limit: 200MB
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  images:
    image: willnorris/imageproxy:latest
    restart: always
    entrypoint:  /go/bin/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers ammobin.ca
  goaccess:
    image: allinurl/goaccess
    volumes:
      - ./goaccess-data/data:/srv/data
      - ./goaccess-data/report:/srv/report
      - ./caddy-logs:/srv/logs
  graphana:
    image: grafana/grafana
    env_file: .env
    restart: always
    volumes:
      - ./graphana:/var/lib/grafana
