version: '2'
services:
  caddy:
    image: abiosoft/caddy:latest
    restart: always
    env_file: .env 
    links:
      - client
      - api
      - images
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy-logs:/var/log/caddy
    ports:
      - 80:80
      - 443:443
    command: --conf  "/etc/Caddyfile"
  client:
    image: ammobindotca/ammobin-client:latest
    restart: always
    ports:
      - 3000
  api:
    env_file: .env 
    image: ammobindotca/ammobin-api:latest
    restart: always
    ports:
      - 8080
    links:
      - redis
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
  images:
    image: willnorris/imageproxy:latest
    restart: always
    entrypoint:  /go/bin/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers ammobin.ca
    ports:
      - 8080

