version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    restart: always
    env_file: .env
    networks:
      - front
    links:
      - client
      - api
      - images
      - graphana
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy-logs:/var/log/caddy
      - ./goaccess-data/report/:/www/goaccess
      - ./caddy-srv/:/srv
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
      - 443:443
    command: --conf  "/etc/Caddyfile"
  client:
    image: ammobindotca/ammobin-client:latest
    restart: always
    networks:
      - front
    deploy:
      resources:
        limits:
          memory: 450M
    depends_on:
      - api
  influx:
    image: influxdb:1.3-alpine
    restart: always
    networks:
      - front
    volumes:
      - ./influx-data/:/var/lib/influxdb
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  api:
    env_file: .env
    image: ammobindotca/ammobin-api:latest
    restart: always
    networks:
      - front
    deploy:
      resources:
        limits:
          memory: 500M
    links:
      - redis
      - influx
    depends_on:
      - redis
      - influx
  worker:
    env_file: .env
    image: ammobindotca/ammobin-worker
    restart: always
    networks:
      - front
    links:
      - redis
      - influx
    depends_on:
      - redis
      - influx
      - api
#    deploy:
 #     placement:
  #      constraints:
   #       - node.role == worker
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - front
    deploy:
      resources:
        limits:
          memory: 200M
      mode: global
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  images:
    image: willnorris/imageproxy:latest
    restart: always
    networks:
      - front
    deploy:
      resources:
        limits:
          memory: 150M
    entrypoint:  /go/bin/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers ammobin.ca
#  goaccess:
#    image: allinurl/goaccess
#    deploy:
#      resources:
#        limits:
#          memory: 75M
#    volumes:
#      - ./goaccess-data/data:/srv/data
#      - ./goaccess-data/report:/srv/report
#      - ./caddy-logs:/srv/logs
#  graphana:
#    image: grafana/grafana
#    env_file: .env
#    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 150M
#      placement:
#        constraints:
      #    - node.role == worker
  #  volumes:
  #    - ./graphana:/var/lib/grafana

networks:
  front:
