version: '3'
services:
  caddy:
    image: abiosoft/caddy
    restart: always
    env_file: .env
    links:
      - client
      - api
      - images
      - graphana
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy-logs:/var/log/caddy
      - ./goaccess/html:/www/goaccess
      - ./caddy-srv/:/srv
    ports:
      - 80:80
      - 443:443
      - 7890:7890
    command: --agree --conf  "/etc/Caddyfile"
  client:
    image: ammobindotca/ammobin-client:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 450M
    depends_on:
      - api
  influx:
    image: influxdb:1.5-alpine
    restart: always
    environment:
     # - INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE=100M
     # - INFLUXDB_DATA_CACHE_SNAPSHOT_MEMORY_SIZE=100M
      - INFLUXDB_DATA_COMPACT_FULL_WRITE_COLD_DURATION=1h
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
    volumes:
      - ./influx-data/:/var/lib/influxdb
  api:
    env_file: .env
    image: ammobindotca/ammobin-api:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    links:
      - redis
      - influx
    depends_on:
      - redis
      - influx
  worker:
    env_file: .env
    image: ammobindotca/ammobin-worker
    restart: always
    links:
      - redis
      - influx
    depends_on:
      - redis
      - influx
      - api
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 200M
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  images:
    image: willnorris/imageproxy:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 150M
    entrypoint:  /go/bin/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers ammobin.ca
  graphana:
    image: grafana/grafana:5.0.4
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 150M
    volumes:
      - ./graphana:/var/lib/grafana
  goaccess:
    image: allinurl/goaccess
    volumes:
      - ./goaccess/data:/srv/data
      - ./goaccess/html:/srv/report
      - ./caddy-logs:/srv/logs
    entrypoint: goaccess --no-global-config --config-file=/srv/data/goaccess.conf --ws-url=wss://stats.ammobin.ca --output=/srv/report/index.html --log-file=/srv/logs/ammobin.log --real-time-html
