version: '3'
services:
  caddy:
    image: ammobindotca/caddy:arm
    restart: always
    env_file: .env
    volumes:
    volumes:
      - caddy-logs:/var/log/ammobin
    networks:
        - outside
        - front
  client:
    image: ammobindotca/ammobin-client:arm
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 450M
    depends_on:
      - api
    networks:
        - front
  api:
    env_file: .env
    image: ammobindotca/ammobin-api:arm
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    depends_on:
      - redis
    networks:
        - front
        - back
  worker:
    env_file: .env
    image: ammobindotca/ammobin-worker:arm
    restart: always
    depends_on:
      - redis
      - api
    networks:
      - back
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - back
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
   images:
    image: ammobindotca/imageproxy:arm
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.platform.arch  == armv7l
    networks:
      - front
    entrypoint: /go/bin/imageproxy -cache /tmp/imageproxy  -addr 0.0.0.0:8080  -referrers pxvwo6gvkk3su5l6.onion,pxvwo6gvkk3su5l6.onion.to
        #fluent
        #hidden service 
  hidden:
    image: memestream/hidden:arm
    secrets:
      - source: private_key
        target: '/var/lib/tor/hidden_service/private_key'
        uid: '100'
        gid: '100'
        mod: 600
    deploy:
      placement:
        constraints:
          - node.platform.arch  == armv7l
          - node.role != manager
    networks:
      - outside
secrets:
  private_key:
    file: ./private_key
  fluent_es_config:
    file: ./fluent_es_config
volumes:
  tor-keys:
    driver: local
  tor:
    driver: local
  caddy-logs:
    driver: local
  fluent-buffer:
    driver: local

networks:
  ? outside
  ? front
  ? back
