{
 "title": "ammobin",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "scrapes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "started",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"started-scrape\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "finished",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"finished-scrape\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "failed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"failed-scrape\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "found items",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.ItemType.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message.items",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "message.type:finished-scrape",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "page loads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: 'track-preformance '",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "click to views",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "alias": "A",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-outbound-click\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-view\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "views to page loads",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "alias": "A",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-view\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: 'track-preformance '",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "clicks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-outbound-click\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "views",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-view\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "clicks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.record.subType.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": "UNKNOWN",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-outbound-click\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "views",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.subType.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": "UNKNOWN",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"track-view\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "clicks by vendor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.record.vendor.keyword",
       "id": "4",
       "settings": { "min_doc_count": 5, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "message.type:\"track-outbound-click\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS + Browser",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ua.browser.family.keyword",
       "id": "5",
       "settings": { "min_doc_count": 25, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "ua.os.family.keyword",
       "id": "4",
       "settings": { "min_doc_count": 5, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "ua.browser.family:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "clicks by item type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.record.itemType.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": "unknown",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "message.type:\"track-outbound-click\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "views by item type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.itemType.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "message.type:\"track-view\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "scrape error log",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.source.keyword",
       "id": "3",
       "settings": { "min_doc_count": 2, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "message.ItemType.keyword",
       "id": "4",
       "settings": { "min_doc_count": 2, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "message.msg.keyword",
       "id": "2",
       "settings": { "min_doc_count": 3, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"failed-scrape\" AND NOT message.msg: \" unknown type*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "no results",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.source.keyword",
       "id": "3",
       "settings": { "min_doc_count": 3, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "no items", "query": "message.items:0" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "message.ItemType.keyword",
       "id": "4",
       "settings": { "min_doc_count": 3, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type:\"finished-scrape\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "keyword searchs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.variables.query.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: \"graphql-query\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "calibre searches",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.variables.subType.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: \"graphql-query\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "vendor searches",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.variables.vendor.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: \"graphql-query\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "province searches",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.variables.province.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: \"graphql-query\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "page",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.variables.page",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: \"graphql-query\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "page size",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.variables.pageSize",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message.type: \"graphql-query\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "http reqs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "code.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "http response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message.path.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "asc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message.timeMs",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "90" ] },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "clientside performance (ms)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message.connectTime",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "90" ] },
       "type": "percentiles"
      },
      {
       "field": "message.interactiveTime",
       "id": "3",
       "meta": {},
       "settings": { "percents": [ "90" ] },
       "type": "percentiles"
      },
      {
       "field": "message.renderTime",
       "id": "4",
       "meta": {},
       "settings": { "percents": [ "90" ] },
       "type": "percentiles"
      }
     ],
     "query": "message.type: 'track-performance'",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}